source 'https://rubygems.org'

# Run this command before launch this application
# bundle install --path vendor/bundle

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.0'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# For CentOS
gem 'therubyracer', platforms: :ruby
# For Mac
# gem 'therubyracer', '0.11.1', platforms: :ruby
# gem 'libv8', '~> 3.11.8.13'

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'

  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

# Aug 20th 2015 https://github.com/twbs/bootstrap-sass
gem 'bootstrap-sass', '~> 3.3.5'
# Aug 21th 2015 http://qiita.com/yumiyon/items/32c6afb5e2e5b7ff369e
gem 'config'
# Aug 27th 2015 https://vitalets.github.io/x-editable/
gem 'x-editable-rails'
# Nov 5th 2015 https://github.com/yamldb/yaml_db
gem 'yaml_db'
# Dec 3rd 2015 https://rubygems.org/gems/rmagick/versions/2.15.4
gem 'rmagick'